/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ru.alejov.study.juliaset;

import java.awt.*;

/**
 *
 * @author admin
 */
public class ProcessForm extends javax.swing.JDialog {

    private final int depth;
    private final int threadCount;
    private final Surface surface;

    /**
     * Creates new form ProcessForm
     */
    public ProcessForm(java.awt.Frame parent, boolean modal, int depth, int threadCount) {
        super(parent, modal);
        this.depth = depth;
        this.threadCount = threadCount;
        initComponents();
        Toolkit defaultToolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = defaultToolkit.getScreenSize();
        int width = Math.min(screenSize.width, 1536);
        int height = Math.min(screenSize.height, 1024);
        this.setPreferredSize(new Dimension(width, height));
        this.setSize(width, height);
        this.surface = new Surface(mainCanvas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainCanvas = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().add(mainCanvas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        startProcess();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        finishProcess();
    }//GEN-LAST:event_formWindowClosing

    private void startProcess() {
        ComplexNumber c = new ComplexNumber(0, 0);
        surface.start(c, getWidth(), getHeight(), depth, threadCount);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas mainCanvas;
    // End of variables declaration//GEN-END:variables

    private void finishProcess() {
        surface.stop();
        dispose();
    }
}
